#设置应用端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.19.134.69:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Abc12345++

# MyBatis
mybatis:
  type-aliases-package: com.example.springboottransactional.domain
  mapper-locations: classpath:/mybatis/*.xml
  #sql打印配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Actuator配置项
management:
  endpoint:
    health:
      show-details: always
